project:
  type: website

website:
  title: "quarto_course"
  navbar:
    left:
      - href: index.qmd
        text: Hello!
      - about.qmd
      - analysis.qmd
      - href: interactive_plot.qmd
        text: static interactive compute!

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



