project:
  type: website

website:
  title: "quarto_course"
  navbar:
    left:
      - href: index.qmd
        text: Hello!
      - about.qmd
      - analysis.qmd
      
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



